package orm;
// Generated Oct 24, 2015 5:41:33 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "\"Product\"")
@XmlRootElement(name="product") 
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4581692578559172216L;
	private String beaconid;
	private String id;
	private String name;
	private Integer price;
	private Long quantity;

	public Product() {
	}

	public Product(String beaconid) {
		this.beaconid = beaconid;
	}

	public Product(String beaconid, String id, String name, Integer price, Long quantity) {
		this.beaconid = beaconid;
		this.id = id;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
	}

	@Id
	@Column(name = "\"beaconid\"", unique = true, nullable = false, length = 50)
	public String getBeaconid() {
		return this.beaconid;
	}

	public void setBeaconid(String beaconid) {
		this.beaconid = beaconid;
	}

	@Column(name = "\"id\"", length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "\"name\"", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "\"price\"", precision = 5, scale = 0)
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "\"quantity\"", precision = 10, scale = 0)
	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}
	
	@Override
	public String toString() {
		StringBuffer toStringBuffer = new StringBuffer("Product Details  = {\n");
		toStringBuffer.append("\tBeaconID :" + this.beaconid +"\n");
		toStringBuffer.append("\tID :" + this.id +"\n");
		toStringBuffer.append("\tName :" + this.name +"\n");
		toStringBuffer.append("\tPrice :" + this.price +"\n");
		toStringBuffer.append("\tQuantity :" + this.quantity +"\n}");
		return toStringBuffer.toString();
	}

}
