package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Beacon generated by hbm2java
 */
@Entity
@Table(name = "BEACON", schema = "SCHOOL")
public class Beacon implements java.io.Serializable {

	private long id;
	private String beaconid;
	private String proximityid;
	private long major;
	private long minor;
	private String name;

	public Beacon() {
	}

	public Beacon(long id, String beaconid, String proximityid, long major, long minor, String name) {
		this.id = id;
		this.beaconid = beaconid;
		this.proximityid = proximityid;
		this.major = major;
		this.minor = minor;
		this.name = name;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "BEACONID", nullable = false, length = 100)
	public String getBeaconid() {
		return this.beaconid;
	}

	public void setBeaconid(String beaconid) {
		this.beaconid = beaconid;
	}

	@Column(name = "PROXIMITYID", nullable = false, length = 50)
	public String getProximityid() {
		return this.proximityid;
	}

	public void setProximityid(String proximityid) {
		this.proximityid = proximityid;
	}

	@Column(name = "MAJOR", nullable = false, precision = 10, scale = 0)
	public long getMajor() {
		return this.major;
	}

	public void setMajor(long major) {
		this.major = major;
	}

	@Column(name = "MINOR", nullable = false, precision = 10, scale = 0)
	public long getMinor() {
		return this.minor;
	}

	public void setMinor(long minor) {
		this.minor = minor;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
