package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChAuditNarrativeVisited generated by hbm2java
 */
@Entity
@Table(name = "CH_AUDIT_NARRATIVE_VISITED", schema = "SCHOOL")
public class ChAuditNarrativeVisited implements java.io.Serializable {

	private ChAuditNarrativeVisitedId id;

	public ChAuditNarrativeVisited() {
	}

	public ChAuditNarrativeVisited(ChAuditNarrativeVisitedId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sequencenumber", column = @Column(name = "SEQUENCENUMBER", nullable = false, precision = 20, scale = 0) ),
			@AttributeOverride(name = "loginid", column = @Column(name = "LOGINID", nullable = false, length = 200) ),
			@AttributeOverride(name = "eventreference", column = @Column(name = "EVENTREFERENCE", nullable = false, length = 200) ),
			@AttributeOverride(name = "timestamp", column = @Column(name = "TIMESTAMP", nullable = false, length = 200) ) })
	public ChAuditNarrativeVisitedId getId() {
		return this.id;
	}

	public void setId(ChAuditNarrativeVisitedId id) {
		this.id = id;
	}

}
