package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChAuditNarrativeVisitedId generated by hbm2java
 */
@Embeddable
public class ChAuditNarrativeVisitedId implements java.io.Serializable {

	private BigDecimal sequencenumber;
	private String loginid;
	private String eventreference;
	private String timestamp;

	public ChAuditNarrativeVisitedId() {
	}

	public ChAuditNarrativeVisitedId(BigDecimal sequencenumber, String loginid, String eventreference,
			String timestamp) {
		this.sequencenumber = sequencenumber;
		this.loginid = loginid;
		this.eventreference = eventreference;
		this.timestamp = timestamp;
	}

	@Column(name = "SEQUENCENUMBER", nullable = false, precision = 20, scale = 0)
	public BigDecimal getSequencenumber() {
		return this.sequencenumber;
	}

	public void setSequencenumber(BigDecimal sequencenumber) {
		this.sequencenumber = sequencenumber;
	}

	@Column(name = "LOGINID", nullable = false, length = 200)
	public String getLoginid() {
		return this.loginid;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	@Column(name = "EVENTREFERENCE", nullable = false, length = 200)
	public String getEventreference() {
		return this.eventreference;
	}

	public void setEventreference(String eventreference) {
		this.eventreference = eventreference;
	}

	@Column(name = "TIMESTAMP", nullable = false, length = 200)
	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChAuditNarrativeVisitedId))
			return false;
		ChAuditNarrativeVisitedId castOther = (ChAuditNarrativeVisitedId) other;

		return ((this.getSequencenumber() == castOther.getSequencenumber())
				|| (this.getSequencenumber() != null && castOther.getSequencenumber() != null
						&& this.getSequencenumber().equals(castOther.getSequencenumber())))
				&& ((this.getLoginid() == castOther.getLoginid()) || (this.getLoginid() != null
						&& castOther.getLoginid() != null && this.getLoginid().equals(castOther.getLoginid())))
				&& ((this.getEventreference() == castOther.getEventreference())
						|| (this.getEventreference() != null && castOther.getEventreference() != null
								&& this.getEventreference().equals(castOther.getEventreference())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null
						&& castOther.getTimestamp() != null && this.getTimestamp().equals(castOther.getTimestamp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSequencenumber() == null ? 0 : this.getSequencenumber().hashCode());
		result = 37 * result + (getLoginid() == null ? 0 : this.getLoginid().hashCode());
		result = 37 * result + (getEventreference() == null ? 0 : this.getEventreference().hashCode());
		result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		return result;
	}

}
