package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChBankuserAuditView generated by hbm2java
 */
@Entity
@Table(name = "CH_BANKUSER_AUDIT_VIEW", schema = "SCHOOL")
public class ChBankuserAuditView implements java.io.Serializable {

	private ChBankuserAuditViewId id;

	public ChBankuserAuditView() {
	}

	public ChBankuserAuditView(ChBankuserAuditViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userLogin", column = @Column(name = "USER_LOGIN", length = 1020) ),
			@AttributeOverride(name = "firstName", column = @Column(name = "FIRST_NAME", length = 4000) ),
			@AttributeOverride(name = "lastName", column = @Column(name = "LAST_NAME", length = 4000) ),
			@AttributeOverride(name = "addLine1", column = @Column(name = "ADD_LINE1", length = 4000) ),
			@AttributeOverride(name = "addLine2", column = @Column(name = "ADD_LINE2", length = 4000) ),
			@AttributeOverride(name = "city", column = @Column(name = "CITY", length = 4000) ),
			@AttributeOverride(name = "state", column = @Column(name = "STATE", length = 4000) ),
			@AttributeOverride(name = "country", column = @Column(name = "COUNTRY", length = 4000) ),
			@AttributeOverride(name = "postalcode", column = @Column(name = "POSTALCODE", scale = 0) ),
			@AttributeOverride(name = "usertype", column = @Column(name = "USERTYPE", length = 4000) ),
			@AttributeOverride(name = "emailid", column = @Column(name = "EMAILID", length = 4000) ),
			@AttributeOverride(name = "mobile", column = @Column(name = "MOBILE", scale = 0) ),
			@AttributeOverride(name = "serviceAccess", column = @Column(name = "SERVICE_ACCESS", length = 4000) ),
			@AttributeOverride(name = "channelCustomer", column = @Column(name = "CHANNEL_CUSTOMER", length = 4000) ),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 200) ),
			@AttributeOverride(name = "action", column = @Column(name = "ACTION", length = 1020) ),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", length = 1020) ),
			@AttributeOverride(name = "createdDateTime", column = @Column(name = "CREATED_DATE_TIME") ),
			@AttributeOverride(name = "lastLoginDateTime", column = @Column(name = "LAST_LOGIN_DATE_TIME", length = 27) ) })
	public ChBankuserAuditViewId getId() {
		return this.id;
	}

	public void setId(ChBankuserAuditViewId id) {
		this.id = id;
	}

}
