package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChBankuserAuditViewId generated by hbm2java
 */
@Embeddable
public class ChBankuserAuditViewId implements java.io.Serializable {

	private String userLogin;
	private String firstName;
	private String lastName;
	private String addLine1;
	private String addLine2;
	private String city;
	private String state;
	private String country;
	private BigDecimal postalcode;
	private String usertype;
	private String emailid;
	private BigDecimal mobile;
	private String serviceAccess;
	private String channelCustomer;
	private String status;
	private String action;
	private String createdBy;
	private Serializable createdDateTime;
	private String lastLoginDateTime;

	public ChBankuserAuditViewId() {
	}

	public ChBankuserAuditViewId(String userLogin, String firstName, String lastName, String addLine1, String addLine2,
			String city, String state, String country, BigDecimal postalcode, String usertype, String emailid,
			BigDecimal mobile, String serviceAccess, String channelCustomer, String status, String action,
			String createdBy, Serializable createdDateTime, String lastLoginDateTime) {
		this.userLogin = userLogin;
		this.firstName = firstName;
		this.lastName = lastName;
		this.addLine1 = addLine1;
		this.addLine2 = addLine2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.postalcode = postalcode;
		this.usertype = usertype;
		this.emailid = emailid;
		this.mobile = mobile;
		this.serviceAccess = serviceAccess;
		this.channelCustomer = channelCustomer;
		this.status = status;
		this.action = action;
		this.createdBy = createdBy;
		this.createdDateTime = createdDateTime;
		this.lastLoginDateTime = lastLoginDateTime;
	}

	@Column(name = "USER_LOGIN", length = 1020)
	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "FIRST_NAME", length = 4000)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 4000)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "ADD_LINE1", length = 4000)
	public String getAddLine1() {
		return this.addLine1;
	}

	public void setAddLine1(String addLine1) {
		this.addLine1 = addLine1;
	}

	@Column(name = "ADD_LINE2", length = 4000)
	public String getAddLine2() {
		return this.addLine2;
	}

	public void setAddLine2(String addLine2) {
		this.addLine2 = addLine2;
	}

	@Column(name = "CITY", length = 4000)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 4000)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", length = 4000)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "POSTALCODE", scale = 0)
	public BigDecimal getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(BigDecimal postalcode) {
		this.postalcode = postalcode;
	}

	@Column(name = "USERTYPE", length = 4000)
	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	@Column(name = "EMAILID", length = 4000)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "MOBILE", scale = 0)
	public BigDecimal getMobile() {
		return this.mobile;
	}

	public void setMobile(BigDecimal mobile) {
		this.mobile = mobile;
	}

	@Column(name = "SERVICE_ACCESS", length = 4000)
	public String getServiceAccess() {
		return this.serviceAccess;
	}

	public void setServiceAccess(String serviceAccess) {
		this.serviceAccess = serviceAccess;
	}

	@Column(name = "CHANNEL_CUSTOMER", length = 4000)
	public String getChannelCustomer() {
		return this.channelCustomer;
	}

	public void setChannelCustomer(String channelCustomer) {
		this.channelCustomer = channelCustomer;
	}

	@Column(name = "STATUS", length = 200)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ACTION", length = 1020)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "CREATED_BY", length = 1020)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE_TIME")
	public Serializable getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Serializable createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "LAST_LOGIN_DATE_TIME", length = 27)
	public String getLastLoginDateTime() {
		return this.lastLoginDateTime;
	}

	public void setLastLoginDateTime(String lastLoginDateTime) {
		this.lastLoginDateTime = lastLoginDateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChBankuserAuditViewId))
			return false;
		ChBankuserAuditViewId castOther = (ChBankuserAuditViewId) other;

		return ((this.getUserLogin() == castOther.getUserLogin()) || (this.getUserLogin() != null
				&& castOther.getUserLogin() != null && this.getUserLogin().equals(castOther.getUserLogin())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getAddLine1() == castOther.getAddLine1()) || (this.getAddLine1() != null
						&& castOther.getAddLine1() != null && this.getAddLine1().equals(castOther.getAddLine1())))
				&& ((this.getAddLine2() == castOther.getAddLine2()) || (this.getAddLine2() != null
						&& castOther.getAddLine2() != null && this.getAddLine2().equals(castOther.getAddLine2())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getPostalcode() == castOther.getPostalcode()) || (this.getPostalcode() != null
						&& castOther.getPostalcode() != null && this.getPostalcode().equals(castOther.getPostalcode())))
				&& ((this.getUsertype() == castOther.getUsertype()) || (this.getUsertype() != null
						&& castOther.getUsertype() != null && this.getUsertype().equals(castOther.getUsertype())))
				&& ((this.getEmailid() == castOther.getEmailid()) || (this.getEmailid() != null
						&& castOther.getEmailid() != null && this.getEmailid().equals(castOther.getEmailid())))
				&& ((this.getMobile() == castOther.getMobile()) || (this.getMobile() != null
						&& castOther.getMobile() != null && this.getMobile().equals(castOther.getMobile())))
				&& ((this.getServiceAccess() == castOther.getServiceAccess())
						|| (this.getServiceAccess() != null && castOther.getServiceAccess() != null
								&& this.getServiceAccess().equals(castOther.getServiceAccess())))
				&& ((this.getChannelCustomer() == castOther.getChannelCustomer())
						|| (this.getChannelCustomer() != null && castOther.getChannelCustomer() != null
								&& this.getChannelCustomer().equals(castOther.getChannelCustomer())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getAction() == castOther.getAction()) || (this.getAction() != null
						&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDateTime() == castOther.getCreatedDateTime())
						|| (this.getCreatedDateTime() != null && castOther.getCreatedDateTime() != null
								&& this.getCreatedDateTime().equals(castOther.getCreatedDateTime())))
				&& ((this.getLastLoginDateTime() == castOther.getLastLoginDateTime())
						|| (this.getLastLoginDateTime() != null && castOther.getLastLoginDateTime() != null
								&& this.getLastLoginDateTime().equals(castOther.getLastLoginDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserLogin() == null ? 0 : this.getUserLogin().hashCode());
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getAddLine1() == null ? 0 : this.getAddLine1().hashCode());
		result = 37 * result + (getAddLine2() == null ? 0 : this.getAddLine2().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getPostalcode() == null ? 0 : this.getPostalcode().hashCode());
		result = 37 * result + (getUsertype() == null ? 0 : this.getUsertype().hashCode());
		result = 37 * result + (getEmailid() == null ? 0 : this.getEmailid().hashCode());
		result = 37 * result + (getMobile() == null ? 0 : this.getMobile().hashCode());
		result = 37 * result + (getServiceAccess() == null ? 0 : this.getServiceAccess().hashCode());
		result = 37 * result + (getChannelCustomer() == null ? 0 : this.getChannelCustomer().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDateTime() == null ? 0 : this.getCreatedDateTime().hashCode());
		result = 37 * result + (getLastLoginDateTime() == null ? 0 : this.getLastLoginDateTime().hashCode());
		return result;
	}

}
