package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChCustomerAuditViewId generated by hbm2java
 */
@Embeddable
public class ChCustomerAuditViewId implements java.io.Serializable {

	private String hostCustomerId;
	private String hostCustomerName;
	private String hostId;
	private String action;
	private String status;
	private String createdBy;
	private Serializable createdDateTime;

	public ChCustomerAuditViewId() {
	}

	public ChCustomerAuditViewId(String hostCustomerId, String hostCustomerName, String hostId, String action,
			String status, String createdBy, Serializable createdDateTime) {
		this.hostCustomerId = hostCustomerId;
		this.hostCustomerName = hostCustomerName;
		this.hostId = hostId;
		this.action = action;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "HOST_CUSTOMER_ID", length = 4000)
	public String getHostCustomerId() {
		return this.hostCustomerId;
	}

	public void setHostCustomerId(String hostCustomerId) {
		this.hostCustomerId = hostCustomerId;
	}

	@Column(name = "HOST_CUSTOMER_NAME", length = 4000)
	public String getHostCustomerName() {
		return this.hostCustomerName;
	}

	public void setHostCustomerName(String hostCustomerName) {
		this.hostCustomerName = hostCustomerName;
	}

	@Column(name = "HOST_ID", length = 4000)
	public String getHostId() {
		return this.hostId;
	}

	public void setHostId(String hostId) {
		this.hostId = hostId;
	}

	@Column(name = "ACTION", length = 4000)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "STATUS", length = 200)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 4000)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE_TIME")
	public Serializable getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Serializable createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChCustomerAuditViewId))
			return false;
		ChCustomerAuditViewId castOther = (ChCustomerAuditViewId) other;

		return ((this.getHostCustomerId() == castOther.getHostCustomerId())
				|| (this.getHostCustomerId() != null && castOther.getHostCustomerId() != null
						&& this.getHostCustomerId().equals(castOther.getHostCustomerId())))
				&& ((this.getHostCustomerName() == castOther.getHostCustomerName())
						|| (this.getHostCustomerName() != null && castOther.getHostCustomerName() != null
								&& this.getHostCustomerName().equals(castOther.getHostCustomerName())))
				&& ((this.getHostId() == castOther.getHostId()) || (this.getHostId() != null
						&& castOther.getHostId() != null && this.getHostId().equals(castOther.getHostId())))
				&& ((this.getAction() == castOther.getAction()) || (this.getAction() != null
						&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDateTime() == castOther.getCreatedDateTime())
						|| (this.getCreatedDateTime() != null && castOther.getCreatedDateTime() != null
								&& this.getCreatedDateTime().equals(castOther.getCreatedDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHostCustomerId() == null ? 0 : this.getHostCustomerId().hashCode());
		result = 37 * result + (getHostCustomerName() == null ? 0 : this.getHostCustomerName().hashCode());
		result = 37 * result + (getHostId() == null ? 0 : this.getHostId().hashCode());
		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDateTime() == null ? 0 : this.getCreatedDateTime().hashCode());
		return result;
	}

}
