package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChGroupAuditViewId generated by hbm2java
 */
@Embeddable
public class ChGroupAuditViewId implements java.io.Serializable {

	private String groupName;
	private String groupDescription;
	private String channelCustomers;
	private String action;
	private String status;
	private String createdBy;
	private Serializable createdDateTime;

	public ChGroupAuditViewId() {
	}

	public ChGroupAuditViewId(String groupName, String groupDescription, String channelCustomers, String action,
			String status, String createdBy, Serializable createdDateTime) {
		this.groupName = groupName;
		this.groupDescription = groupDescription;
		this.channelCustomers = channelCustomers;
		this.action = action;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "GROUP_NAME", length = 4000)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "GROUP_DESCRIPTION", length = 4000)
	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	@Column(name = "CHANNEL_CUSTOMERS", length = 4000)
	public String getChannelCustomers() {
		return this.channelCustomers;
	}

	public void setChannelCustomers(String channelCustomers) {
		this.channelCustomers = channelCustomers;
	}

	@Column(name = "ACTION", length = 4000)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "STATUS", length = 200)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 4000)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE_TIME")
	public Serializable getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Serializable createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChGroupAuditViewId))
			return false;
		ChGroupAuditViewId castOther = (ChGroupAuditViewId) other;

		return ((this.getGroupName() == castOther.getGroupName()) || (this.getGroupName() != null
				&& castOther.getGroupName() != null && this.getGroupName().equals(castOther.getGroupName())))
				&& ((this.getGroupDescription() == castOther.getGroupDescription())
						|| (this.getGroupDescription() != null && castOther.getGroupDescription() != null
								&& this.getGroupDescription().equals(castOther.getGroupDescription())))
				&& ((this.getChannelCustomers() == castOther.getChannelCustomers())
						|| (this.getChannelCustomers() != null && castOther.getChannelCustomers() != null
								&& this.getChannelCustomers().equals(castOther.getChannelCustomers())))
				&& ((this.getAction() == castOther.getAction()) || (this.getAction() != null
						&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDateTime() == castOther.getCreatedDateTime())
						|| (this.getCreatedDateTime() != null && castOther.getCreatedDateTime() != null
								&& this.getCreatedDateTime().equals(castOther.getCreatedDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGroupName() == null ? 0 : this.getGroupName().hashCode());
		result = 37 * result + (getGroupDescription() == null ? 0 : this.getGroupDescription().hashCode());
		result = 37 * result + (getChannelCustomers() == null ? 0 : this.getChannelCustomers().hashCode());
		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDateTime() == null ? 0 : this.getCreatedDateTime().hashCode());
		return result;
	}

}
