package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChGroupAuditView generated by hbm2java
 */
@Entity
@Table(name = "CH_GROUP_AUDIT_VIEW", schema = "SCHOOL")
public class ChGroupAuditView implements java.io.Serializable {

	private ChGroupAuditViewId id;

	public ChGroupAuditView() {
	}

	public ChGroupAuditView(ChGroupAuditViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "groupName", column = @Column(name = "GROUP_NAME", length = 4000) ),
			@AttributeOverride(name = "groupDescription", column = @Column(name = "GROUP_DESCRIPTION", length = 4000) ),
			@AttributeOverride(name = "channelCustomers", column = @Column(name = "CHANNEL_CUSTOMERS", length = 4000) ),
			@AttributeOverride(name = "action", column = @Column(name = "ACTION", length = 4000) ),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 200) ),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", length = 4000) ),
			@AttributeOverride(name = "createdDateTime", column = @Column(name = "CREATED_DATE_TIME") ) })
	public ChGroupAuditViewId getId() {
		return this.id;
	}

	public void setId(ChGroupAuditViewId id) {
		this.id = id;
	}

}
