package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChServicesAuditViewId generated by hbm2java
 */
@Embeddable
public class ChServicesAuditViewId implements java.io.Serializable {

	private String serviceAccessName;
	private String serviceAccessDescription;
	private String servicesId;
	private String action;
	private String status;
	private String createdBy;
	private Serializable createdDateTime;

	public ChServicesAuditViewId() {
	}

	public ChServicesAuditViewId(String serviceAccessName, String serviceAccessDescription, String servicesId,
			String action, String status, String createdBy, Serializable createdDateTime) {
		this.serviceAccessName = serviceAccessName;
		this.serviceAccessDescription = serviceAccessDescription;
		this.servicesId = servicesId;
		this.action = action;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "SERVICE_ACCESS_NAME", length = 4000)
	public String getServiceAccessName() {
		return this.serviceAccessName;
	}

	public void setServiceAccessName(String serviceAccessName) {
		this.serviceAccessName = serviceAccessName;
	}

	@Column(name = "SERVICE_ACCESS_DESCRIPTION", length = 4000)
	public String getServiceAccessDescription() {
		return this.serviceAccessDescription;
	}

	public void setServiceAccessDescription(String serviceAccessDescription) {
		this.serviceAccessDescription = serviceAccessDescription;
	}

	@Column(name = "SERVICES_ID", length = 4000)
	public String getServicesId() {
		return this.servicesId;
	}

	public void setServicesId(String servicesId) {
		this.servicesId = servicesId;
	}

	@Column(name = "ACTION", length = 4000)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "STATUS", length = 200)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 4000)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE_TIME")
	public Serializable getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Serializable createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChServicesAuditViewId))
			return false;
		ChServicesAuditViewId castOther = (ChServicesAuditViewId) other;

		return ((this.getServiceAccessName() == castOther.getServiceAccessName())
				|| (this.getServiceAccessName() != null && castOther.getServiceAccessName() != null
						&& this.getServiceAccessName().equals(castOther.getServiceAccessName())))
				&& ((this.getServiceAccessDescription() == castOther.getServiceAccessDescription())
						|| (this.getServiceAccessDescription() != null
								&& castOther.getServiceAccessDescription() != null
								&& this.getServiceAccessDescription().equals(castOther.getServiceAccessDescription())))
				&& ((this.getServicesId() == castOther.getServicesId()) || (this.getServicesId() != null
						&& castOther.getServicesId() != null && this.getServicesId().equals(castOther.getServicesId())))
				&& ((this.getAction() == castOther.getAction()) || (this.getAction() != null
						&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDateTime() == castOther.getCreatedDateTime())
						|| (this.getCreatedDateTime() != null && castOther.getCreatedDateTime() != null
								&& this.getCreatedDateTime().equals(castOther.getCreatedDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getServiceAccessName() == null ? 0 : this.getServiceAccessName().hashCode());
		result = 37 * result
				+ (getServiceAccessDescription() == null ? 0 : this.getServiceAccessDescription().hashCode());
		result = 37 * result + (getServicesId() == null ? 0 : this.getServicesId().hashCode());
		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDateTime() == null ? 0 : this.getCreatedDateTime().hashCode());
		return result;
	}

}
