package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "COURSE", schema = "SCHOOL")
public class Course implements java.io.Serializable {

	private BigDecimal courseid;
	private String coursename;

	public Course() {
	}

	public Course(BigDecimal courseid) {
		this.courseid = courseid;
	}

	public Course(BigDecimal courseid, String coursename) {
		this.courseid = courseid;
		this.coursename = coursename;
	}

	@Id

	@Column(name = "COURSEID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCourseid() {
		return this.courseid;
	}

	public void setCourseid(BigDecimal courseid) {
		this.courseid = courseid;
	}

	@Column(name = "COURSENAME", length = 100)
	public String getCoursename() {
		return this.coursename;
	}

	public void setCoursename(String coursename) {
		this.coursename = coursename;
	}

}
