package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CrwCaRspnsFileDetails generated by hbm2java
 */
@Entity
@Table(name = "CRW_CA_RSPNS_FILE_DETAILS", schema = "SCHOOL")
public class CrwCaRspnsFileDetails implements java.io.Serializable {

	private CrwCaRspnsFileDetailsId id;

	public CrwCaRspnsFileDetails() {
	}

	public CrwCaRspnsFileDetails(CrwCaRspnsFileDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "crwSecaccno", column = @Column(name = "CRW_SECACCNO", length = 16) ),
			@AttributeOverride(name = "crwUploadfilename", column = @Column(name = "CRW_UPLOADFILENAME", length = 100) ) })
	public CrwCaRspnsFileDetailsId getId() {
		return this.id;
	}

	public void setId(CrwCaRspnsFileDetailsId id) {
		this.id = id;
	}

}
