package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrwCaRspnsAudit generated by hbm2java
 */
@Entity
@Table(name = "CRW_CA_RSPNS_AUDIT", schema = "SCHOOL")
public class CrwCaRspnsAudit implements java.io.Serializable {

	private CrwCaRspnsAuditId id;
	private String crwCaId;
	private String crwClientRef;
	private Long crwNcsRefNum;
	private String crwSecId;
	private String crwScaId;
	private Integer crwOptnSeq;
	private String crwOptnDesc;
	private BigDecimal crwEligibleQty;
	private BigDecimal crwAdvsdQty;
	private Integer crwSiInd;
	private Date crwEntryDt;
	private String crwRmrks;
	private Integer crwSta;
	private Integer crwStaCd;
	private Integer crwPrevSta;
	private String crwStaDesc;
	private BigDecimal crwPndingAproval;
	private BigDecimal crwOvrSubsQty;
	private String crwTndrPricTyp;
	private Integer crwPriceTypCd;
	private BigDecimal crwTndrPrice;
	private Date modificationDate;
	private Short crwCaRspnsVer;
	private String branchid;
	private String userid;
	private String crwRjctnRsn;
	private String crwFiller1;
	private String crwFiller5;
	private String crwFiller6;
	private BigDecimal crwFiller7;
	private BigDecimal crwFiller8;
	private String crwFiller9;
	private String modifiedby;
	private String crwUpldfilename;
	private Short versionnum;
	private String crwAuthby;
	private String crwSecName;
	private String cancClntRefer;
	private String crwBansrefnum;
	private String crwFunctionofmsg;
	private String crwEvntTyp;
	private String action;
	private Serializable creationDate;

	public CrwCaRspnsAudit() {
	}

	public CrwCaRspnsAudit(CrwCaRspnsAuditId id, Serializable creationDate) {
		this.id = id;
		this.creationDate = creationDate;
	}

	public CrwCaRspnsAudit(CrwCaRspnsAuditId id, String crwCaId, String crwClientRef, Long crwNcsRefNum,
			String crwSecId, String crwScaId, Integer crwOptnSeq, String crwOptnDesc, BigDecimal crwEligibleQty,
			BigDecimal crwAdvsdQty, Integer crwSiInd, Date crwEntryDt, String crwRmrks, Integer crwSta,
			Integer crwStaCd, Integer crwPrevSta, String crwStaDesc, BigDecimal crwPndingAproval,
			BigDecimal crwOvrSubsQty, String crwTndrPricTyp, Integer crwPriceTypCd, BigDecimal crwTndrPrice,
			Date modificationDate, Short crwCaRspnsVer, String branchid, String userid, String crwRjctnRsn,
			String crwFiller1, String crwFiller5, String crwFiller6, BigDecimal crwFiller7, BigDecimal crwFiller8,
			String crwFiller9, String modifiedby, String crwUpldfilename, Short versionnum, String crwAuthby,
			String crwSecName, String cancClntRefer, String crwBansrefnum, String crwFunctionofmsg, String crwEvntTyp,
			String action, Serializable creationDate) {
		this.id = id;
		this.crwCaId = crwCaId;
		this.crwClientRef = crwClientRef;
		this.crwNcsRefNum = crwNcsRefNum;
		this.crwSecId = crwSecId;
		this.crwScaId = crwScaId;
		this.crwOptnSeq = crwOptnSeq;
		this.crwOptnDesc = crwOptnDesc;
		this.crwEligibleQty = crwEligibleQty;
		this.crwAdvsdQty = crwAdvsdQty;
		this.crwSiInd = crwSiInd;
		this.crwEntryDt = crwEntryDt;
		this.crwRmrks = crwRmrks;
		this.crwSta = crwSta;
		this.crwStaCd = crwStaCd;
		this.crwPrevSta = crwPrevSta;
		this.crwStaDesc = crwStaDesc;
		this.crwPndingAproval = crwPndingAproval;
		this.crwOvrSubsQty = crwOvrSubsQty;
		this.crwTndrPricTyp = crwTndrPricTyp;
		this.crwPriceTypCd = crwPriceTypCd;
		this.crwTndrPrice = crwTndrPrice;
		this.modificationDate = modificationDate;
		this.crwCaRspnsVer = crwCaRspnsVer;
		this.branchid = branchid;
		this.userid = userid;
		this.crwRjctnRsn = crwRjctnRsn;
		this.crwFiller1 = crwFiller1;
		this.crwFiller5 = crwFiller5;
		this.crwFiller6 = crwFiller6;
		this.crwFiller7 = crwFiller7;
		this.crwFiller8 = crwFiller8;
		this.crwFiller9 = crwFiller9;
		this.modifiedby = modifiedby;
		this.crwUpldfilename = crwUpldfilename;
		this.versionnum = versionnum;
		this.crwAuthby = crwAuthby;
		this.crwSecName = crwSecName;
		this.cancClntRefer = cancClntRefer;
		this.crwBansrefnum = crwBansrefnum;
		this.crwFunctionofmsg = crwFunctionofmsg;
		this.crwEvntTyp = crwEvntTyp;
		this.action = action;
		this.creationDate = creationDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "txnid", column = @Column(name = "TXNID", nullable = false, precision = 18, scale = 0) ),
			@AttributeOverride(name = "imagetype", column = @Column(name = "IMAGETYPE", nullable = false, length = 8) ) })
	public CrwCaRspnsAuditId getId() {
		return this.id;
	}

	public void setId(CrwCaRspnsAuditId id) {
		this.id = id;
	}

	@Column(name = "CRW_CA_ID", length = 16)
	public String getCrwCaId() {
		return this.crwCaId;
	}

	public void setCrwCaId(String crwCaId) {
		this.crwCaId = crwCaId;
	}

	@Column(name = "CRW_CLIENT_REF", length = 16)
	public String getCrwClientRef() {
		return this.crwClientRef;
	}

	public void setCrwClientRef(String crwClientRef) {
		this.crwClientRef = crwClientRef;
	}

	@Column(name = "CRW_NCS_REF_NUM", precision = 12, scale = 0)
	public Long getCrwNcsRefNum() {
		return this.crwNcsRefNum;
	}

	public void setCrwNcsRefNum(Long crwNcsRefNum) {
		this.crwNcsRefNum = crwNcsRefNum;
	}

	@Column(name = "CRW_SEC_ID", length = 25)
	public String getCrwSecId() {
		return this.crwSecId;
	}

	public void setCrwSecId(String crwSecId) {
		this.crwSecId = crwSecId;
	}

	@Column(name = "CRW_SCA_ID", length = 20)
	public String getCrwScaId() {
		return this.crwScaId;
	}

	public void setCrwScaId(String crwScaId) {
		this.crwScaId = crwScaId;
	}

	@Column(name = "CRW_OPTN_SEQ", precision = 8, scale = 0)
	public Integer getCrwOptnSeq() {
		return this.crwOptnSeq;
	}

	public void setCrwOptnSeq(Integer crwOptnSeq) {
		this.crwOptnSeq = crwOptnSeq;
	}

	@Column(name = "CRW_OPTN_DESC", length = 36)
	public String getCrwOptnDesc() {
		return this.crwOptnDesc;
	}

	public void setCrwOptnDesc(String crwOptnDesc) {
		this.crwOptnDesc = crwOptnDesc;
	}

	@Column(name = "CRW_ELIGIBLE_QTY", precision = 36, scale = 4)
	public BigDecimal getCrwEligibleQty() {
		return this.crwEligibleQty;
	}

	public void setCrwEligibleQty(BigDecimal crwEligibleQty) {
		this.crwEligibleQty = crwEligibleQty;
	}

	@Column(name = "CRW_ADVSD_QTY", precision = 36, scale = 4)
	public BigDecimal getCrwAdvsdQty() {
		return this.crwAdvsdQty;
	}

	public void setCrwAdvsdQty(BigDecimal crwAdvsdQty) {
		this.crwAdvsdQty = crwAdvsdQty;
	}

	@Column(name = "CRW_SI_IND", precision = 8, scale = 0)
	public Integer getCrwSiInd() {
		return this.crwSiInd;
	}

	public void setCrwSiInd(Integer crwSiInd) {
		this.crwSiInd = crwSiInd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRW_ENTRY_DT", length = 7)
	public Date getCrwEntryDt() {
		return this.crwEntryDt;
	}

	public void setCrwEntryDt(Date crwEntryDt) {
		this.crwEntryDt = crwEntryDt;
	}

	@Column(name = "CRW_RMRKS")
	public String getCrwRmrks() {
		return this.crwRmrks;
	}

	public void setCrwRmrks(String crwRmrks) {
		this.crwRmrks = crwRmrks;
	}

	@Column(name = "CRW_STA", precision = 8, scale = 0)
	public Integer getCrwSta() {
		return this.crwSta;
	}

	public void setCrwSta(Integer crwSta) {
		this.crwSta = crwSta;
	}

	@Column(name = "CRW_STA_CD", precision = 8, scale = 0)
	public Integer getCrwStaCd() {
		return this.crwStaCd;
	}

	public void setCrwStaCd(Integer crwStaCd) {
		this.crwStaCd = crwStaCd;
	}

	@Column(name = "CRW_PREV_STA", precision = 8, scale = 0)
	public Integer getCrwPrevSta() {
		return this.crwPrevSta;
	}

	public void setCrwPrevSta(Integer crwPrevSta) {
		this.crwPrevSta = crwPrevSta;
	}

	@Column(name = "CRW_STA_DESC", length = 36)
	public String getCrwStaDesc() {
		return this.crwStaDesc;
	}

	public void setCrwStaDesc(String crwStaDesc) {
		this.crwStaDesc = crwStaDesc;
	}

	@Column(name = "CRW_PNDING_APROVAL", precision = 36, scale = 0)
	public BigDecimal getCrwPndingAproval() {
		return this.crwPndingAproval;
	}

	public void setCrwPndingAproval(BigDecimal crwPndingAproval) {
		this.crwPndingAproval = crwPndingAproval;
	}

	@Column(name = "CRW_OVR_SUBS_QTY", precision = 36, scale = 4)
	public BigDecimal getCrwOvrSubsQty() {
		return this.crwOvrSubsQty;
	}

	public void setCrwOvrSubsQty(BigDecimal crwOvrSubsQty) {
		this.crwOvrSubsQty = crwOvrSubsQty;
	}

	@Column(name = "CRW_TNDR_PRIC_TYP", length = 8)
	public String getCrwTndrPricTyp() {
		return this.crwTndrPricTyp;
	}

	public void setCrwTndrPricTyp(String crwTndrPricTyp) {
		this.crwTndrPricTyp = crwTndrPricTyp;
	}

	@Column(name = "CRW_PRICE_TYP_CD", precision = 8, scale = 0)
	public Integer getCrwPriceTypCd() {
		return this.crwPriceTypCd;
	}

	public void setCrwPriceTypCd(Integer crwPriceTypCd) {
		this.crwPriceTypCd = crwPriceTypCd;
	}

	@Column(name = "CRW_TNDR_PRICE", precision = 15, scale = 6)
	public BigDecimal getCrwTndrPrice() {
		return this.crwTndrPrice;
	}

	public void setCrwTndrPrice(BigDecimal crwTndrPrice) {
		this.crwTndrPrice = crwTndrPrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFICATION_DATE", length = 7)
	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	@Column(name = "CRW_CA_RSPNS_VER", precision = 4, scale = 0)
	public Short getCrwCaRspnsVer() {
		return this.crwCaRspnsVer;
	}

	public void setCrwCaRspnsVer(Short crwCaRspnsVer) {
		this.crwCaRspnsVer = crwCaRspnsVer;
	}

	@Column(name = "BRANCHID", length = 2)
	public String getBranchid() {
		return this.branchid;
	}

	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}

	@Column(name = "USERID", length = 101)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "CRW_RJCTN_RSN")
	public String getCrwRjctnRsn() {
		return this.crwRjctnRsn;
	}

	public void setCrwRjctnRsn(String crwRjctnRsn) {
		this.crwRjctnRsn = crwRjctnRsn;
	}

	@Column(name = "CRW_FILLER_1", length = 36)
	public String getCrwFiller1() {
		return this.crwFiller1;
	}

	public void setCrwFiller1(String crwFiller1) {
		this.crwFiller1 = crwFiller1;
	}

	@Column(name = "CRW_FILLER_5", length = 20)
	public String getCrwFiller5() {
		return this.crwFiller5;
	}

	public void setCrwFiller5(String crwFiller5) {
		this.crwFiller5 = crwFiller5;
	}

	@Column(name = "CRW_FILLER_6", length = 65)
	public String getCrwFiller6() {
		return this.crwFiller6;
	}

	public void setCrwFiller6(String crwFiller6) {
		this.crwFiller6 = crwFiller6;
	}

	@Column(name = "CRW_FILLER_7", precision = 31, scale = 10)
	public BigDecimal getCrwFiller7() {
		return this.crwFiller7;
	}

	public void setCrwFiller7(BigDecimal crwFiller7) {
		this.crwFiller7 = crwFiller7;
	}

	@Column(name = "CRW_FILLER_8", precision = 18, scale = 4)
	public BigDecimal getCrwFiller8() {
		return this.crwFiller8;
	}

	public void setCrwFiller8(BigDecimal crwFiller8) {
		this.crwFiller8 = crwFiller8;
	}

	@Column(name = "CRW_FILLER_9")
	public String getCrwFiller9() {
		return this.crwFiller9;
	}

	public void setCrwFiller9(String crwFiller9) {
		this.crwFiller9 = crwFiller9;
	}

	@Column(name = "MODIFIEDBY", length = 101)
	public String getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

	@Column(name = "CRW_UPLDFILENAME", length = 105)
	public String getCrwUpldfilename() {
		return this.crwUpldfilename;
	}

	public void setCrwUpldfilename(String crwUpldfilename) {
		this.crwUpldfilename = crwUpldfilename;
	}

	@Column(name = "VERSIONNUM", precision = 4, scale = 0)
	public Short getVersionnum() {
		return this.versionnum;
	}

	public void setVersionnum(Short versionnum) {
		this.versionnum = versionnum;
	}

	@Column(name = "CRW_AUTHBY", length = 101)
	public String getCrwAuthby() {
		return this.crwAuthby;
	}

	public void setCrwAuthby(String crwAuthby) {
		this.crwAuthby = crwAuthby;
	}

	@Column(name = "CRW_SEC_NAME", length = 105)
	public String getCrwSecName() {
		return this.crwSecName;
	}

	public void setCrwSecName(String crwSecName) {
		this.crwSecName = crwSecName;
	}

	@Column(name = "CANC_CLNT_REFER", length = 16)
	public String getCancClntRefer() {
		return this.cancClntRefer;
	}

	public void setCancClntRefer(String cancClntRefer) {
		this.cancClntRefer = cancClntRefer;
	}

	@Column(name = "CRW_BANSREFNUM", length = 36)
	public String getCrwBansrefnum() {
		return this.crwBansrefnum;
	}

	public void setCrwBansrefnum(String crwBansrefnum) {
		this.crwBansrefnum = crwBansrefnum;
	}

	@Column(name = "CRW_FUNCTIONOFMSG", length = 4)
	public String getCrwFunctionofmsg() {
		return this.crwFunctionofmsg;
	}

	public void setCrwFunctionofmsg(String crwFunctionofmsg) {
		this.crwFunctionofmsg = crwFunctionofmsg;
	}

	@Column(name = "CRW_EVNT_TYP", length = 40)
	public String getCrwEvntTyp() {
		return this.crwEvntTyp;
	}

	public void setCrwEvntTyp(String crwEvntTyp) {
		this.crwEvntTyp = crwEvntTyp;
	}

	@Column(name = "ACTION", length = 8)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public Serializable getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Serializable creationDate) {
		this.creationDate = creationDate;
	}

}
