package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CrwCaRspnsFileDetailsId generated by hbm2java
 */
@Embeddable
public class CrwCaRspnsFileDetailsId implements java.io.Serializable {

	private String crwSecaccno;
	private String crwUploadfilename;

	public CrwCaRspnsFileDetailsId() {
	}

	public CrwCaRspnsFileDetailsId(String crwSecaccno, String crwUploadfilename) {
		this.crwSecaccno = crwSecaccno;
		this.crwUploadfilename = crwUploadfilename;
	}

	@Column(name = "CRW_SECACCNO", length = 16)
	public String getCrwSecaccno() {
		return this.crwSecaccno;
	}

	public void setCrwSecaccno(String crwSecaccno) {
		this.crwSecaccno = crwSecaccno;
	}

	@Column(name = "CRW_UPLOADFILENAME", length = 100)
	public String getCrwUploadfilename() {
		return this.crwUploadfilename;
	}

	public void setCrwUploadfilename(String crwUploadfilename) {
		this.crwUploadfilename = crwUploadfilename;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CrwCaRspnsFileDetailsId))
			return false;
		CrwCaRspnsFileDetailsId castOther = (CrwCaRspnsFileDetailsId) other;

		return ((this.getCrwSecaccno() == castOther.getCrwSecaccno()) || (this.getCrwSecaccno() != null
				&& castOther.getCrwSecaccno() != null && this.getCrwSecaccno().equals(castOther.getCrwSecaccno())))
				&& ((this.getCrwUploadfilename() == castOther.getCrwUploadfilename())
						|| (this.getCrwUploadfilename() != null && castOther.getCrwUploadfilename() != null
								&& this.getCrwUploadfilename().equals(castOther.getCrwUploadfilename())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCrwSecaccno() == null ? 0 : this.getCrwSecaccno().hashCode());
		result = 37 * result + (getCrwUploadfilename() == null ? 0 : this.getCrwUploadfilename().hashCode());
		return result;
	}

}
