package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductBackupId generated by hbm2java
 */
@Embeddable
public class ProductBackupId implements java.io.Serializable {

	private String id;
	private String name;
	private Integer price;
	private Long quantity;
	private String beaconid;

	public ProductBackupId() {
	}

	public ProductBackupId(String id, String name, Integer price, Long quantity, String beaconid) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.beaconid = beaconid;
	}

	@Column(name = "ID", length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRICE", precision = 5, scale = 0)
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "QUANTITY", precision = 10, scale = 0)
	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	@Column(name = "BEACONID", length = 50)
	public String getBeaconid() {
		return this.beaconid;
	}

	public void setBeaconid(String beaconid) {
		this.beaconid = beaconid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductBackupId))
			return false;
		ProductBackupId castOther = (ProductBackupId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getPrice() == castOther.getPrice()) || (this.getPrice() != null
						&& castOther.getPrice() != null && this.getPrice().equals(castOther.getPrice())))
				&& ((this.getQuantity() == castOther.getQuantity()) || (this.getQuantity() != null
						&& castOther.getQuantity() != null && this.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getBeaconid() == castOther.getBeaconid()) || (this.getBeaconid() != null
						&& castOther.getBeaconid() != null && this.getBeaconid().equals(castOther.getBeaconid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result + (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37 * result + (getBeaconid() == null ? 0 : this.getBeaconid().hashCode());
		return result;
	}

}
