package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductBackup generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_BACKUP", schema = "SCHOOL")
public class ProductBackup implements java.io.Serializable {

	private ProductBackupId id;

	public ProductBackup() {
	}

	public ProductBackup(ProductBackupId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", length = 10) ),
			@AttributeOverride(name = "name", column = @Column(name = "NAME", length = 100) ),
			@AttributeOverride(name = "price", column = @Column(name = "PRICE", precision = 5, scale = 0) ),
			@AttributeOverride(name = "quantity", column = @Column(name = "QUANTITY", precision = 10, scale = 0) ),
			@AttributeOverride(name = "beaconid", column = @Column(name = "BEACONID", length = 50) ) })
	public ProductBackupId getId() {
		return this.id;
	}

	public void setId(ProductBackupId id) {
		this.id = id;
	}

}
