package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * SchUser generated by hbm2java
 */
@Entity
@Table(name = "SCH_USER", schema = "SCHOOL")
public class SchUser implements java.io.Serializable {

	private BigDecimal userid;
	private String username;
	private String password;
	private Short age;
	private Long zipcode;
	private Set<SchCourse> schCourses = new HashSet<SchCourse>(0);

	public SchUser() {
	}

	public SchUser(BigDecimal userid, String username, String password) {
		this.userid = userid;
		this.username = username;
		this.password = password;
	}

	public SchUser(BigDecimal userid, String username, String password, Short age, Long zipcode,
			Set<SchCourse> schCourses) {
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.age = age;
		this.zipcode = zipcode;
		this.schCourses = schCourses;
	}

	@Id

	@Column(name = "USERID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUserid() {
		return this.userid;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}

	@Column(name = "USERNAME", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "AGE", precision = 3, scale = 0)
	public Short getAge() {
		return this.age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	@Column(name = "ZIPCODE", precision = 10, scale = 0)
	public Long getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Long zipcode) {
		this.zipcode = zipcode;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SCH_COURSE_ENRLMNT", schema = "SCHOOL", joinColumns = {
			@JoinColumn(name = "USERID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "COURSEID", nullable = false, updatable = false) })
	public Set<SchCourse> getSchCourses() {
		return this.schCourses;
	}

	public void setSchCourses(Set<SchCourse> schCourses) {
		this.schCourses = schCourses;
	}

}
