package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SmtbVAcnttypeAcntMappingId generated by hbm2java
 */
@Embeddable
public class SmtbVAcnttypeAcntMappingId implements java.io.Serializable {

	private int accounttypeid;
	private String accounttypename;
	private String accountid;

	public SmtbVAcnttypeAcntMappingId() {
	}

	public SmtbVAcnttypeAcntMappingId(int accounttypeid, String accounttypename) {
		this.accounttypeid = accounttypeid;
		this.accounttypename = accounttypename;
	}

	public SmtbVAcnttypeAcntMappingId(int accounttypeid, String accounttypename, String accountid) {
		this.accounttypeid = accounttypeid;
		this.accounttypename = accounttypename;
		this.accountid = accountid;
	}

	@Column(name = "ACCOUNTTYPEID", nullable = false, precision = 5, scale = 0)
	public int getAccounttypeid() {
		return this.accounttypeid;
	}

	public void setAccounttypeid(int accounttypeid) {
		this.accounttypeid = accounttypeid;
	}

	@Column(name = "ACCOUNTTYPENAME", nullable = false, length = 40)
	public String getAccounttypename() {
		return this.accounttypename;
	}

	public void setAccounttypename(String accounttypename) {
		this.accounttypename = accounttypename;
	}

	@Column(name = "ACCOUNTID", length = 40)
	public String getAccountid() {
		return this.accountid;
	}

	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SmtbVAcnttypeAcntMappingId))
			return false;
		SmtbVAcnttypeAcntMappingId castOther = (SmtbVAcnttypeAcntMappingId) other;

		return (this.getAccounttypeid() == castOther.getAccounttypeid())
				&& ((this.getAccounttypename() == castOther.getAccounttypename())
						|| (this.getAccounttypename() != null && castOther.getAccounttypename() != null
								&& this.getAccounttypename().equals(castOther.getAccounttypename())))
				&& ((this.getAccountid() == castOther.getAccountid()) || (this.getAccountid() != null
						&& castOther.getAccountid() != null && this.getAccountid().equals(castOther.getAccountid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccounttypeid();
		result = 37 * result + (getAccounttypename() == null ? 0 : this.getAccounttypename().hashCode());
		result = 37 * result + (getAccountid() == null ? 0 : this.getAccountid().hashCode());
		return result;
	}

}
