package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SmtbVAcnttypeAcntMapping generated by hbm2java
 */
@Entity
@Table(name = "SMTB_V_ACNTTYPE_ACNT_MAPPING", schema = "SCHOOL")
public class SmtbVAcnttypeAcntMapping implements java.io.Serializable {

	private SmtbVAcnttypeAcntMappingId id;

	public SmtbVAcnttypeAcntMapping() {
	}

	public SmtbVAcnttypeAcntMapping(SmtbVAcnttypeAcntMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accounttypeid", column = @Column(name = "ACCOUNTTYPEID", nullable = false, precision = 5, scale = 0) ),
			@AttributeOverride(name = "accounttypename", column = @Column(name = "ACCOUNTTYPENAME", nullable = false, length = 40) ),
			@AttributeOverride(name = "accountid", column = @Column(name = "ACCOUNTID", length = 40) ) })
	public SmtbVAcnttypeAcntMappingId getId() {
		return this.id;
	}

	public void setId(SmtbVAcnttypeAcntMappingId id) {
		this.id = id;
	}

}
