package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SmtbVUserAcnttypeMapping generated by hbm2java
 */
@Entity
@Table(name = "SMTB_V_USER_ACNTTYPE_MAPPING", schema = "SCHOOL")
public class SmtbVUserAcnttypeMapping implements java.io.Serializable {

	private SmtbVUserAcnttypeMappingId id;

	public SmtbVUserAcnttypeMapping() {
	}

	public SmtbVUserAcnttypeMapping(SmtbVUserAcnttypeMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "USERNAME", nullable = false, length = 400) ),
			@AttributeOverride(name = "accounttypeid", column = @Column(name = "ACCOUNTTYPEID", nullable = false, precision = 5, scale = 0) ),
			@AttributeOverride(name = "accounttypename", column = @Column(name = "ACCOUNTTYPENAME", nullable = false, length = 40) ) })
	public SmtbVUserAcnttypeMappingId getId() {
		return this.id;
	}

	public void setId(SmtbVUserAcnttypeMappingId id) {
		this.id = id;
	}

}
