package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SumiAcntgrpmaster generated by hbm2java
 */
@Entity
@Table(name = "SUMI_ACNTGRPMASTER", schema = "SCHOOL")
public class SumiAcntgrpmaster implements java.io.Serializable {

	private String id;
	private String acntgroupid;
	private String acntgroupname;

	public SumiAcntgrpmaster() {
	}

	public SumiAcntgrpmaster(String id, String acntgroupid, String acntgroupname) {
		this.id = id;
		this.acntgroupid = acntgroupid;
		this.acntgroupname = acntgroupname;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ACNTGROUPID", nullable = false, length = 5)
	public String getAcntgroupid() {
		return this.acntgroupid;
	}

	public void setAcntgroupid(String acntgroupid) {
		this.acntgroupid = acntgroupid;
	}

	@Column(name = "ACNTGROUPNAME", nullable = false, length = 40)
	public String getAcntgroupname() {
		return this.acntgroupname;
	}

	public void setAcntgroupname(String acntgroupname) {
		this.acntgroupname = acntgroupname;
	}

}
