package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SumiUserAcnttypeMapping generated by hbm2java
 */
@Entity
@Table(name = "SUMI_USER_ACNTTYPE_MAPPING", schema = "SCHOOL")
public class SumiUserAcnttypeMapping implements java.io.Serializable {

	private SumiUserAcnttypeMappingId id;

	public SumiUserAcnttypeMapping() {
	}

	public SumiUserAcnttypeMapping(SumiUserAcnttypeMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "loginId", column = @Column(name = "LOGIN_ID", nullable = false, length = 100) ),
			@AttributeOverride(name = "accttypeid", column = @Column(name = "ACCTTYPEID", nullable = false, precision = 5, scale = 0) ) })
	public SumiUserAcnttypeMappingId getId() {
		return this.id;
	}

	public void setId(SumiUserAcnttypeMappingId id) {
		this.id = id;
	}

}
