package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SumiUserAcntgrpMappingId generated by hbm2java
 */
@Embeddable
public class SumiUserAcntgrpMappingId implements java.io.Serializable {

	private String loginId;
	private Integer acntgroupid;

	public SumiUserAcntgrpMappingId() {
	}

	public SumiUserAcntgrpMappingId(String loginId) {
		this.loginId = loginId;
	}

	public SumiUserAcntgrpMappingId(String loginId, Integer acntgroupid) {
		this.loginId = loginId;
		this.acntgroupid = acntgroupid;
	}

	@Column(name = "LOGIN_ID", nullable = false, length = 100)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "ACNTGROUPID", precision = 5, scale = 0)
	public Integer getAcntgroupid() {
		return this.acntgroupid;
	}

	public void setAcntgroupid(Integer acntgroupid) {
		this.acntgroupid = acntgroupid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SumiUserAcntgrpMappingId))
			return false;
		SumiUserAcntgrpMappingId castOther = (SumiUserAcntgrpMappingId) other;

		return ((this.getLoginId() == castOther.getLoginId()) || (this.getLoginId() != null
				&& castOther.getLoginId() != null && this.getLoginId().equals(castOther.getLoginId())))
				&& ((this.getAcntgroupid() == castOther.getAcntgroupid())
						|| (this.getAcntgroupid() != null && castOther.getAcntgroupid() != null
								&& this.getAcntgroupid().equals(castOther.getAcntgroupid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLoginId() == null ? 0 : this.getLoginId().hashCode());
		result = 37 * result + (getAcntgroupid() == null ? 0 : this.getAcntgroupid().hashCode());
		return result;
	}

}
