package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SumiUserAcnttypeMappingId generated by hbm2java
 */
@Embeddable
public class SumiUserAcnttypeMappingId implements java.io.Serializable {

	private String loginId;
	private int accttypeid;

	public SumiUserAcnttypeMappingId() {
	}

	public SumiUserAcnttypeMappingId(String loginId, int accttypeid) {
		this.loginId = loginId;
		this.accttypeid = accttypeid;
	}

	@Column(name = "LOGIN_ID", nullable = false, length = 100)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "ACCTTYPEID", nullable = false, precision = 5, scale = 0)
	public int getAccttypeid() {
		return this.accttypeid;
	}

	public void setAccttypeid(int accttypeid) {
		this.accttypeid = accttypeid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SumiUserAcnttypeMappingId))
			return false;
		SumiUserAcnttypeMappingId castOther = (SumiUserAcnttypeMappingId) other;

		return ((this.getLoginId() == castOther.getLoginId()) || (this.getLoginId() != null
				&& castOther.getLoginId() != null && this.getLoginId().equals(castOther.getLoginId())))
				&& (this.getAccttypeid() == castOther.getAccttypeid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLoginId() == null ? 0 : this.getLoginId().hashCode());
		result = 37 * result + this.getAccttypeid();
		return result;
	}

}
