package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SumiAcntgrpAcntMappingId generated by hbm2java
 */
@Embeddable
public class SumiAcntgrpAcntMappingId implements java.io.Serializable {

	private int acntgroupid;
	private BigDecimal channelCustId;

	public SumiAcntgrpAcntMappingId() {
	}

	public SumiAcntgrpAcntMappingId(int acntgroupid, BigDecimal channelCustId) {
		this.acntgroupid = acntgroupid;
		this.channelCustId = channelCustId;
	}

	@Column(name = "ACNTGROUPID", nullable = false, precision = 5, scale = 0)
	public int getAcntgroupid() {
		return this.acntgroupid;
	}

	public void setAcntgroupid(int acntgroupid) {
		this.acntgroupid = acntgroupid;
	}

	@Column(name = "CHANNEL_CUST_ID", nullable = false, scale = 0)
	public BigDecimal getChannelCustId() {
		return this.channelCustId;
	}

	public void setChannelCustId(BigDecimal channelCustId) {
		this.channelCustId = channelCustId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SumiAcntgrpAcntMappingId))
			return false;
		SumiAcntgrpAcntMappingId castOther = (SumiAcntgrpAcntMappingId) other;

		return (this.getAcntgroupid() == castOther.getAcntgroupid())
				&& ((this.getChannelCustId() == castOther.getChannelCustId())
						|| (this.getChannelCustId() != null && castOther.getChannelCustId() != null
								&& this.getChannelCustId().equals(castOther.getChannelCustId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAcntgroupid();
		result = 37 * result + (getChannelCustId() == null ? 0 : this.getChannelCustId().hashCode());
		return result;
	}

}
