package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SumiAcnttypemaster generated by hbm2java
 */
@Entity
@Table(name = "SUMI_ACNTTYPEMASTER", schema = "SCHOOL")
public class SumiAcnttypemaster implements java.io.Serializable {

	private String id;
	private int accttypeid;
	private String accttypename;

	public SumiAcnttypemaster() {
	}

	public SumiAcnttypemaster(String id, int accttypeid, String accttypename) {
		this.id = id;
		this.accttypeid = accttypeid;
		this.accttypename = accttypename;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ACCTTYPEID", nullable = false, precision = 5, scale = 0)
	public int getAccttypeid() {
		return this.accttypeid;
	}

	public void setAccttypeid(int accttypeid) {
		this.accttypeid = accttypeid;
	}

	@Column(name = "ACCTTYPENAME", nullable = false, length = 40)
	public String getAccttypename() {
		return this.accttypename;
	}

	public void setAccttypename(String accttypename) {
		this.accttypename = accttypename;
	}

}
