package orm;
// Generated Oct 24, 2015 11:26:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SumiUserAcntgrpMapping generated by hbm2java
 */
@Entity
@Table(name = "SUMI_USER_ACNTGRP_MAPPING", schema = "SCHOOL")
public class SumiUserAcntgrpMapping implements java.io.Serializable {

	private SumiUserAcntgrpMappingId id;

	public SumiUserAcntgrpMapping() {
	}

	public SumiUserAcntgrpMapping(SumiUserAcntgrpMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "loginId", column = @Column(name = "LOGIN_ID", nullable = false, length = 100) ),
			@AttributeOverride(name = "acntgroupid", column = @Column(name = "ACNTGROUPID", precision = 5, scale = 0) ) })
	public SumiUserAcntgrpMappingId getId() {
		return this.id;
	}

	public void setId(SumiUserAcntgrpMappingId id) {
		this.id = id;
	}

}
